apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ai-agent-service
  title: AI Agent Service
  description: Scaffold AI-agent deployment service with Helm + policies
  annotations:
    # ✅ 强制使用 v3 表达式引擎（启用 ${{ }}）
    scaffolder.backstage.io/templatingEngine: v3
spec:
  owner: ai-platform
  type: service
  parameters:
    - title: Basics
      required: [name, owner, env, repoOwner, repoName]
      properties:
        name:
          type: string
          description: Service name
        owner:
          type: string
          default: ai-platform
        env:
          type: string
          enum: [dev, staging, prod]
        repoOwner:
          type: string
          description: org/owner (e.g. OrgPY)
        repoName:
          type: string
          description: repo name (e.g. sample-repo)

  steps:
    - id: fetch
      name: Fetch skeleton from remote
      action: fetch:template
      input:
        # ✅ 远程目录 URL（Backstage UrlReader 会拉整个目录树）
        url: https://github.com/OrgPY/backstage-template/tree/master/skeleton
        values:
          name:  ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          env:   ${{ parameters.env }}
          repoOwner: ${{ parameters.repoOwner }}
          repoName:  ${{ parameters.repoName }}

    - id: publish
      name: Open PR with generated files
      action: publish:github:pull-request
      input:
        # ✅ 用 v3 表达式解析 owner/repo
        repoUrl: >-
          github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repoName }}
        # ✅ 生成合法分支名：小写 + 仅保留 0-9A-Za-z._-，其他转为 -
        # scaffold/${{ parameters.name.toLowerCase().replace(/[^0-9A-Za-z._-]/g, '-') }}-${{ parameters.env.toLowerCase() }}
        branchName: >-
          ${{ parameters.env.toLowerCase() }}
        title: >-
          Scaffold ${{ parameters.name }} (${{ parameters.env }})
        description: >-
          Generated by Backstage AI Agent template
        # 可选：把文件放到 repo 子目录。不加则落在仓库根目录。
        # targetPath: services/${{ parameters.name.toLowerCase().replace(/[^0-9A-Za-z._-]/g, '-') }}
