apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ai-agent-service
  title: AI Agent Service
  description: Scaffold AI-agent deployment service with Helm + policies
spec:
  owner: ai-platform
  type: service
  parameters:
    - title: Basics
      required: [name, owner, env, repoOwner, repoName]
      properties:
        name:
          type: string
          description: Service name
        owner:
          type: string
          default: ai-platform
        env:
          type: string
          enum: [dev, staging, prod]
        repoOwner:
          type: string
          description: org/owner
        repoName:
          type: string
          description: repo name
  steps:
    - id: fetch
      name: Fetch skeleton from remote
      action: fetch:template
      input:
        # ✅ 用 GitHub 目录 URL（tree 或 blob 都行，Backstage 会通过 UrlReader 拉取整目录）
        url: https://github.com/OrgPY/backstage-template/tree/master/skeleton
        # 如果你用 default 分支叫 master，就把 main 改成 master
        values:
          name: '{{ parameters.name }}'
          owner: '{{ parameters.owner }}'
          env: '{{ parameters.env }}'
          repo: '{{ parameters.repo }}'
    - id: publish
      name: Open PR with generated files
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repoName }}
        branchName: 'scaffold/{{ parameters.name }}-{{ parameters.env }}'
        title: 'Scaffold {{ parameters.name }} ({{ parameters.env }})'
        description: 'Generated by Backstage AI Agent template'
        # targetPath: '/'
    - id: done
      name: Done
      action: core:log
      input:
        message: 'Template completed'
