apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ai-agent-service
  title: AI Agent Service
  description: Scaffold a new AI Agent service with Helm + GitOps + policies
spec:
  owner: ai-platform
  type: service
  parameters:
    - title: Basics
      required: [name, owner, env, repo]
      properties:
        name:
          type: string
          description: Service name
        owner:
          type: string
          default: ai-platform
        env:
          type: string
          enum: [dev, staging, prod]
        repo:
          type: string
          description: GitHub repo in the form your-org/your-repo
  steps:
    - id: fetch
      name: Fetch skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: '{{ parameters.name }}'
          owner: '{{ parameters.owner }}'
          env: '{{ parameters.env }}'
          repo: '{{ parameters.repo }}'
    - id: publish
      name: Create PR with generated files
      action: publish:github:pull-request
      input:
        repoUrl: 'github.com?owner={{ parameters.repo.split("/")[0] }}&repo={{ parameters.repo.split("/")[1] }}'
        branchName: 'scaffold/{{ parameters.name }}-{{ parameters.env }}'
        title: 'Scaffold {{ parameters.name }} ({{ parameters.env }})'
        description: 'Generated by Backstage AI Agent template'
        targetPath: '/'
    - id: done
      name: Done
      action: core:log
      input:
        message: 'Template completed'
